version: "2.3"

services:
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # plex media server
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${PLEX_TRANSCODE_DIR}:/transcode
      - ${MOVIES_DIR}:/data/movies
      - ${TV_DIR}:/data/tv
      - ${PLEX_PREROLLS_DIR}:/data/prerolls
    environment:
      - TZ=Europe/London
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  # tautulli
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    volumes:
      - ${CONFIG_DIR}/plexpy:/config
      - ${CONFIG_DIR}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.frontend.rule=Host:tautulli.${LOCAL_DOMAIN}"
    restart: unless-stopped

  # ombi
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    volumes:
      - ${CONFIG_DIR}/ombi:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.frontend.rule=Host:ombi.${LOCAL_DOMAIN}"
    restart: unless-stopped

  # nzbget
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - ${CONFIG_DIR}/nzbget:/config
      - ${DOWNLOADS_DIR}/complete:/complete
      - ${DOWNLOADS_DIR}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.frontend.rule=Host:nzbget.${LOCAL_DOMAIN}"
    restart: unless-stopped

  hydra:
    image: linuxserver/hydra2
    container_name: hydra
    volumes:
      - ${CONFIG_DIR}/hydra:/config
    labels:
      - "traefik.frontend.rule=Host:nzbhydra.${LOCAL_DOMAIN}"
    restart: unless-stopped

  # sonarr
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${TV_DIR}:/tv
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.frontend.rule=Host:sonarr.${LOCAL_DOMAIN}"
    cpus: 0.5
    restart: unless-stopped

  # radarr
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MOVIES_DIR}:/movies
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.frontend.rule=Host:radarr.${LOCAL_DOMAIN}"
    cpus: 0.5
    restart: unless-stopped

  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - ${CONFIG_DIR}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule "* 15 */12 * * *"
    restart: unless-stopped
