version: "2.3"

services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    volumes:
      - ${CONFIG_DIR}/nzbget:/config
      - ${MEDIA_DIR}/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "6789:6789"
    restart: unless-stopped

  hydra:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: hydra
    volumes:
      - ${CONFIG_DIR}/hydra:/config
    ports:
      - "5076:5076"
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr:nightly
    container_name: radarr
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MEDIA_DIR}:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "7878:7878"
    restart: unless-stopped
