version: "2.3"

services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "9117:9117"
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${MEDIA_DIR}/downloads:/downloads
    restart: unless-stopped

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${MEDIA_DIR}/downloads/files:/downloads
      - ${MEDIA_DIR}/downloads/watch:/watch
    ports:
      - "9091:9091"
      - "56408:51413/tcp"
      - "56408:51413/udp"
    dns: "8.8.8.8"
    restart: unless-stopped

  # sonarr
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "8989:8989"
    restart: unless-stopped

  # radarr
  radarr:
    image: ghcr.io/linuxserver/radarr:nightly
    container_name: radarr
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MEDIA_DIR}:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "7878:7878"
    restart: unless-stopped
