version: "2.3"

services:
  # plex media server
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${PLEX_TRANSCODE_DIR}:/transcode
      - ${MEDIA_DIR}:/media
    ports:
      - 32400:32400
    environment:
      - TZ=Europe/London
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    network-mode: "service:[vpn]"
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${MEDIA_DIR}/downloads:/downloads
    restart: unless-stopped

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    network-mode: "service:[vpn]"
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${MEDIA_DIR}/downloads/files:/downloads
      - ${MEDIA_DIR}/downloads/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
    restart: unless-stopped

  # sonarr
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 8989:8989
    restart: unless-stopped

  # radarr
  radarr:
    image: ghcr.io/linuxserver/radarr:nightly
    container_name: radarr
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MEDIA_DIR}:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 7878:7878
    restart: unless-stopped
    
  # VPN
  vpn:
    image: ghcr.io/linuxserver/openvpn-as
    cap_add:
      - NET_ADMIN
    container_name: vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "943:943"
      - "9443:9443"
      - "1194:1194/udp"
      - "9117:9117" # jackett
    volumes:
      - ${CONFIG_DIR}/openvpn:/config
    restart: unless-stopped
    
